export const SET_CURRENCY = 'SET_CURRENCY';
export const SET_CATEGORY = 'SET_CATEGORY';
export const SELECT_PRODUCT = 'SELECT_PRODUCT';
export const REMOVE_PRODUCT = 'REMOVE_PRODUCTS';
export const ADD_TO_CART = 'ADD_TO_CART';
export const UPDATE_PRODUCT_CARD = 'UPDATE_PRODUCT_CARD';
export const DELETE_PRODUCT_CART = 'DELETE_PRODUCT_CART';
export const TOGGLE_CART_POPUP = 'TOGGLE_CART_POPUP';
